name: "Шаблон отчета о дефекте"
description: "Используйте этот шаблон для создания отчетов о дефектах."
title: "[Ошибка]: "
labels: ["bug"]

body:
  - type: textarea
    id: defect_title
    attributes:
      label: "Заголовок"
      description: "Краткое описание проблемы."
      placeholder: "Введите заголовок дефекта..."
    validations:
      required: true

  - type: textarea
    id: defect_description
    attributes:
      label: "Описание"
      description: "Подробное описание проблемы, с которой вы столкнулись."
      placeholder: "Опишите дефект здесь..."
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: "Шаги воспроизведения"
      description: "Опишите шаги, которые необходимо выполнить для воспроизведения дефекта."
      placeholder: "Введите шаги воспроизведения..."
    validations:
      required: true

  - type: textarea
    id: expected_result
    attributes:
      label: "Ожидаемый результат"
      description: "Опишите, что должно произойти."
      placeholder: "Введите ожидаемый результат..."
    validations:
      required: true

  - type: textarea
    id: actual_result
    attributes:
      label: "Фактический результат"
      description: "Опишите, что произошло на самом деле."
      placeholder: "Введите фактический результат..."
    validations:
      required: true

  - type: textarea
    id: additional_materials
    attributes:
      label: "Скриншоты / Доп. материалы"
      description: "Прикрепите скриншоты или дополнительные материалы, если есть."
      placeholder: "Введите ссылки на скриншоты или дополнительные материалы..."
  
  - type: dropdown
    id: environment
    attributes:
      label: "Среда выполнения"
      description: "Выберите среду, в которой возник дефект."
      options:
        - "Windows 11"
        - "macOS"
        - "Linux"
        - "Android"
        - "iOS"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: "Опасность"
      description: "Выберите уровень опасноти дефекта."
      options:
        - "Низкая"
        - "Средняя"
        - "Высокая"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Пожалуйста, предоставьте как можно больше информации о дефекте, чтобы помочь нам его исправить.
